# Generated by Django 4.2.6 on 2023-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_user_booking_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
