# Generated by Django 4.2.6 on 2023-10-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
