# Generated by Django 4.2.6 on 2023-10-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_cancellation_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_policy',
        ),
    ]
